{
	"version": 1638764156,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/bgmenu-sheet0.png",
		"images/play-sheet0.png",
		"images/bglevel-sheet0.png",
		"images/huruf-sheet0.png",
		"images/huruf-sheet1.png",
		"images/huruf-sheet2.png",
		"images/jawaban-sheet0.png",
		"images/tempathuruf-sheet0.png",
		"images/bendera-sheet0.png",
		"images/bendera-sheet1.png",
		"images/bendera-sheet2.png",
		"images/bendera-sheet3.png",
		"images/layerhitam-sheet0.png",
		"images/good-sheet0.png",
		"images/next_button-sheet0.png",
		"images/bgexit-sheet0.png",
		"images/exitbutton-sheet0.png",
		"media/backsound kids, anak-anak no copyright.m4a",
		"media/backsound kids, anak-anak no copyright.ogg",
		"media/children yay! sound effect (mp3cut.net).m4a",
		"media/children yay! sound effect (mp3cut.net).ogg",
		"media/bubble, pop sound effect.m4a",
		"media/bubble, pop sound effect.ogg",
		"media/🎶backsound ceria _ aesthetic no (blue sky).m4a",
		"media/🎶backsound ceria _ aesthetic no (blue sky).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}